version: '2'
services:
  rabbitmq:
      image: macintoshplus/rabbitmq-management:latest
      container_name: rabbitmq
      restart: always
      networks:
        - springcloud-network
      dns_search: .
      environment:
       - RABBITMQ_DEFAULT_USER=admin
       - RABBITMQ_DEFAULT_PASS=admin
      ports:
        - 5672:5672
        - 15672:15672
  eureka-server:
    image: springcloud/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8181:8181
  config-server:
    image: springcloud/spring-cloud-config-server:0.0.1-SNAPSHOT
    container_name: config-server
    restart: always
    volumes:
      -  /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8185:8185
    depends_on:
      - eureka-server
  eureka-client:
    image: springcloud/eureka-client:0.0.1-SNAPSHOT
    container_name: eureka-client
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8182:8182
    depends_on:
      - eureka-server
  eureka-client1:
    image: springcloud/eureka-client:0.0.1-SNAPSHOT
    container_name: eureka-client1
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 18182:8182
    depends_on:
      - eureka-server
  eureka-consumer-fegin:
    image: springcloud/eureka-consumer-feign:0.0.1-SNAPSHOT
    container_name: eureka-consumer-feign
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8184:8184
    depends_on:
      - eureka-server
      - rabbitmq
  eureka-consumer-fegin1:
    image: springcloud/eureka-consumer-feign:0.0.1-SNAPSHOT
    container_name: eureka-consumer-feign1
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 18184:8184
    depends_on:
      - eureka-server
      - rabbitmq
  turbine:
    image: springcloud/turbine:0.0.1-SNAPSHOT
    container_name: turbine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8187:8187
      - 8287:8287
    depends_on:
      - eureka-server
      - rabbitmq
  api-gateway:
    image: springcloud/api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8188:8188
    depends_on:
      - eureka-server
  hystrix-dashboard:
    image: springcloud/hystrix-dashboard:0.0.1-SNAPSHOT
    container_name: hystrix-dashboard
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - springcloud-network
    dns_search: .
    ports:
      - 8186:8186
networks:
  springcloud-network:
    external: false
